export const emailField = '[data-qa="login-email"]'
export const passwordField = '[data-qa="login-password"]'
export const signinBtn = '[data-qa="login-button"]'
export const invalidEmailAlert = '.message-error'
export const signupNameField = '[data-qa="signup-name"]'
export const signupEmailField = '[data-qa="signup-email"]'
export const signupBtn = '[data-qa="signup-button"]'